#ifndef __MIXTREEPROB_H 
#define __MIXTREEPROB_H 
 
#include <stdlib.h> 
#include <stdio.h>	 
#include "Popul.h" 

//#include "treeprob.h" 
 
class MixtureRegions{ 
	 public: 
  
     
	 int  NumberVars;           // Number of Variables 
	 int  NumberRegions;        // Number of Regions 
         int  NumberPoints;         // Number of Points in the population 
         int  CNumberPoints;        // Condensed number of points 
         int  CNumberRegions; 
         int  Count; // Number of final steps during learning 
         double BestLikehood;  
         double BestProb;  //Probability of the best 
         Popul *AllPoints;      // Population of points fitted 
	 //Popul *FinalPoints;         // Population of points generated by the mixture 
     DynFDA* MyMarkovNet;AbstractProbModel **EveryRegion;      // Mixture Components (Regions) 
	 double *lambdavalues;     // Mixture Coefficients 
         double *baselambdavalues;     // auxiliary mixture Coefficients 
         double  lsup; // Gain of a jump in learning  
         double ** Probabilities; 
         double * ExtraTotProb;
         double *RegionProb;     // Tot. Probability given by the tree to the points in the pop (no normalization); 
          
         double MeanMixtProb; //Idem above but for the whole Mixture 
         double MaxMixtProb; // A limit to MixtProb 
	 int InitialLambda;    // How initial Lambdas are initialized 
	                       // 0- Uniform 
	                       // 1- Proportional to Fitness from Regions 
	 double* PopProb;     //Prob. of the dif. vectors in the population 
	 int MaxLearningSteps;  //Maximum number of steps for the Learning Alg.  
	 double *LikehoodValues; // Likehood values of every step 
	 int StopCrit;            // Stop criteria for the Learning Alg. 
                             // 0- Number of steps 
							 // 1- A given threshold for the likehood 
							 // 2- A given threshold for the difference of the likehood of consecutive steps 
         int LearningSteps; 
	 double LearningThreshold; 
         double SelInt; 
         int Prior; 
         double CurrentILikehood; 
         int MixtComplexity;
        
	 MixtureRegions(int,int,int,int,int,double,double,double,int); 
	 virtual ~MixtureRegions(); 
	 void SetPop(Popul*); 
	 void SetRegions(int, AbstractProbModel*); 
	 void FindInitCoefficients(); 
	 void UniformLambdas();  
         void RandomLambdas();	 
	 //void FitnessPropLambdas(); 
	 void FillProbabilities(); 
         void NormalizeProb(); 
	 void FindGammaValues();
         void UpdateTotProb();
	 void UpdateRegionsProb();  
         void FindCurrentCoefficients();
         void Printlambdas(double*,int);
         void Setlambdas(double*,int);
	 void PrintProb(); 
	     virtual void LearningMixtureMeila(); 
	     virtual void LearningMixture(int);
         void MixturesInit(int,int,double*,double);
         virtual void MixturesInitMeila(int,double*,double);
       	 void SamplingFromMixture(Popul*);  
         double Prob (unsigned* vector); 
         double  CalculateOptimalLikehood();
         double  CalculateILikehood(int); 
         virtual void    CalProb(); 
         void    FillProbabilities(int); 
         void   FindICurrentCoefficients();
         void   SetNpoints(int, double*); 
         void CalcMixtProb(int, double*,double*); 
         void UpdateTotProb(double*);  
         virtual void RemoveRegions();
         virtual void RemoveProbabilities();
         void PutPriors();
}; 

