
#ifndef __MIXTREEPROB_H 
#define __MIXTREEPROB_H 
 
#include <stdlib.h> 
#include <stdio.h>	 
#include "Popul.h" 
#include "AbstractTree.h" 
//#include "treeprob.h" 
 
class MixtureTrees{ 
	 public: 
  
	       
	 int  NumberVars;           // Number of Variables 
	 int  NumberTrees;         // Number of Trees 
         int  NumberPoints;         // Number of Points in the population 
         int  CNumberPoints;         // Condensed number of points 
         int  CNumberTrees; 
         int  Count; // Number of final steps during learning 
         double BestLikehood;  
         double BestProb;  //Probability of the best 
         Popul *AllPoints;      // Population of points fitted 
	 //Popul *FinalPoints;         // Population of points generated by the mixture 
     AbstractProbModel **EveryTree;      // Mixture Components (Trees) 
	 double *lambdavalues;     // Mixture Coefficients 
         double *baselambdavalues;     // auxiliary mixture Coefficients 
         double  lsup; // Gain of a jump in learning  
         double ** Probabilities; 
         double * ExtraTotProb;
         double *TreeProb;     // Tot. Probability given by the tree to the points in the pop (no normalization); 
          
         double* Smooth_alpha; // alpha values for smoothing 
         double MeanMixtProb; //Idem above but for the whole Mixture 
         double MaxMixtProb; // A limit to MixtProb 
	 int InitialLambda;    // How initial Lambdas are initialized 
	                       // 0- Uniform 
	                       // 1- Proportional to Fitness from Trees 
	 double* PopProb;     //Prob. of the dif. vectors in the population 
	 int MaxLearningSteps;  //Maximum number of steps for the Learning Alg.  
	 double *LikehoodValues; // Likehood values of every step 
	 int StopCrit;            // Stop criteria for the Learning Alg. 
                             // 0- Number of steps 
							 // 1- A given threshold for the likehood 
							 // 2- A given threshold for the difference of the likehood of consecutive steps 
        int LearningSteps; 
	 double LearningThreshold; 
         double Smoothing; 
         double SelInt; 
         int Prior; 
         double CurrentILikehood; 
         int MixtComplexity;
        
  
	 MixtureTrees(int,int,int,int,int,double,double,double,int); 
	 virtual ~MixtureTrees(); 
	 void SetPop(Popul*); 
	 void SetTrees(int, AbstractProbModel*); 
	 void FindInitCoefficients(); 
	 void UniformLambdas();  
         void RandomLambdas();	 
	 //void FitnessPropLambdas(); 
	 void FillProbabilities(); 
         void FillEqualProbabilities();
         void FillProbabilitiesSimple();  
         void FillProbabilitiesSimple(int); 
         void NormalizeProb(); 
	 void FindGammaValues();
         void UpdateTotProb();
	 void UpdateTreesProb();  
         void UpdateForestProb(); 
	 void FindCurrentCoefficients();
         void Printlambdas(double*,int);
         void Setlambdas(double*,int);
	     void FindCurrentCoefficients(double*,int); 
         void PrintProb(); 
	     virtual void LearningMixtureMeila(); 
	     virtual void LearningMixture(int);
         virtual void LearningMixture(int,int);  
         virtual void   LearningMixtureGreedy(); 
         virtual void   LearningMixtureGreedy1();
         void   LearningMixtureExact(int,double);      
         void MixturesInit(int,int,double*,double,int,int,int,int);
         virtual void MixturesInitMeila(int,double*,double);
         void MixturesInitKikuchi(double*,double,int,int,int,int);
         virtual void MixturesInitGreedy(int,double*,double);
         virtual void MixturesInitProd(int,double*, double);
	 void CalculateLikehood(int); 
         void Calculate_Smooth_alpha(); 
	 int StopCriteria(int); 
	 void SetStopCriteria(int,int,double); 
         void SamplingIndividual(Popul*,int,int);
	 void SamplingFromMixture(Popul*);  
         void SamplingFromMixtureCycles(Popul*);
         virtual void SamplingFromMixtureMixt(Popul*); 
         virtual void SamplingFromMixtureHMixing(Popul*);
	 double Prob (unsigned* vector); 
         double Calculate_Best_Prior(int,int,double); 
         int NextStructure(); 
         int NextStructure1(); 
         double  CalculateGain(int); 
         double  CalculateGainEnlargedM(int); 
         double  CalculateOptimalLikehood();
         double  CalculateILikehood(int); 
         virtual void    CalProb(); 
         void    FillProbabilities(int); 
         void    FillProbabilitiesSimple(int,int);
         void    InitNumberTrees();	 
         void   FinishNumberTrees();	 
         void   EnlargeMixture(); 
         void   FindICurrentCoefficients();
         void   FindCoefficientsFromMI();
         virtual void   SubstractProb(int); 
         void   SetNpoints(int, double*); 
         virtual double FindParamIndep(double*,double*, double*);
         virtual double FindParamDep(double*,double*,double,int, double*);
         virtual double FindAllParamDep(double*,double*, double,double,double*);
         void   Normalize_Param(double* );
         double SearchStructure(double,int*,int,int,double);
         void UpdateCoefAfterAddition(int);
         void UpdateCoefAfterAddition_false(int);
         void CalcMixtProb(int, double*,double*); 
         void UpdateTotProb(double*);  
         void UpdateCoefAfterAddition_trad(int,int);
         virtual int FindParams(int, double*,double *, double, double, double* );
     	 double CalculateILikehood(double*, int , int* , double*, double*,int);
         double CalculateQuadError(double*, double* , int, int* , double* , double*);
         double CalculateMDL(double*, int, int*, double*, double*,int,int, double);
         virtual void NewTreeStructure();
         virtual void RemoveTrees();
         virtual void RemoveProbabilities();
         void Findvar_assig(int,int,int*);
         void PutPriors();
         void Destroy();
}; 


class MixtureIntTrees: public MixtureTrees{ 
	 public: 
      unsigned int* Card;
  
	 MixtureIntTrees(int,int,int,int,int,double,double,double,int,unsigned int*); 
         virtual ~MixtureIntTrees();                                     	 
      
	 	
         virtual void MixturesInitMeila(int,double*,double);
         virtual void MixturesInitGreedy(int,double*,double);
         virtual void MixturesInitProd(int,double*, double);   
	 virtual void    CalProb();           
	 //virtual void SamplingFromMixtureMixt(Popul*){}; 
	 //virtual void SamplingFromMixtureHMixing(Popul*){};               
         virtual void   SubstractProb(int);  
         virtual void RemoveTrees();  
     	        
}; 


#endif  
 
 
 
