"""
compare_eda_cluster.py — compare BN learning algorithms on the extended EDA
benchmark from the tidy CSV produced by ``scripts/extract_eda_cluster.py``.

The **Spearman correlation** (``sp``) between the BN-predicted probability and
the original Boltzmann probability is the *priority* metric for ranking the
algorithms: it measures how faithfully a learned BN reproduces the target
probability ordering, which is exactly what an EDA needs.

Because the three data splits are *different selection-pressure regimes* (the
objective distribution shifts from split 0 to split 2), predicting a split that
was not used for learning is a genuine out-of-regime generalisation test.  For a
run trained on split ``t`` we therefore separate:

  * **train**  — correlation on split ``t`` itself, and
  * **test**   — correlation on the two held-out splits (the two "test cases").

Outputs (under ``results/eda_cluster_analysis/``)
    tables/   *.tex   — LaTeX tables (booktabs), best value bold per column
    figures/  *.pdf   — publication figures (no titles; captions live in LaTeX)

Usage
-----
    python3 scripts/compare_eda_cluster.py [results_csv] [out_dir]
"""
from __future__ import annotations

import os
import sys
import warnings

import numpy as np
import pandas as pd

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy.stats import kruskal, spearmanr  # noqa: F401
try:
    import scikit_posthocs as sp_posthoc
    _HAVE_DUNN = True
except Exception:                            # noqa: BLE001
    _HAVE_DUNN = False

warnings.filterwarnings("ignore", message="Mean of empty slice")
warnings.filterwarnings("ignore", message="All-NaN slice encountered")

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ---------------------------------------------------------------------------
# Presentation constants
# ---------------------------------------------------------------------------
plt.rcParams.update({
    "font.size": 15, "axes.labelsize": 17, "axes.titlesize": 15,
    "xtick.labelsize": 13, "ytick.labelsize": 13, "legend.fontsize": 12,
    "figure.dpi": 110, "savefig.bbox": "tight", "pdf.fonttype": 42,
    "axes.grid": True, "grid.alpha": 0.3,
})

# pretty labels + a stable display order (baseline first, K2 family, others)
PRETTY = {
    "univ_bn": "Univ", "k2": "K2", "k2_mi": "K2-MI", "k2_mb": "K2-MB",
    "k2_refine": "K2-Ref", "k2_ensemble": "K2-Ens", "k2_plus": "K2+",
    "fi_k2": "FI-K2", "rfe_k2": "RFE-K2", "bic": "BIC-HC", "aic": "AIC-HC",
    "stable_hc": "HC-Stb", "pc": "PC", "stable_pc": "PC-Stb", "dt": "DT",
    "dmbbn": "DMBBN", "sartre": "SARTRE", "binotears": "BINO", "bounded_tw": "BdTW",
}
GROUP_ORDER = ["small", "medium", "large"]
TEMP_ORDER = ["0.1", "1.0", "10"]


def pretty(a):
    return PRETTY.get(a, a)


# ---------------------------------------------------------------------------
# LaTeX helpers
# ---------------------------------------------------------------------------

def _fmt(x, prec=3):
    if x is None or (isinstance(x, float) and (np.isnan(x))):
        return "--"
    return f"{x:.{prec}f}"


def latex_table(df_disp, path, caption, label, higher_better=None, prec=3,
                index_name="Algorithm", note=None):
    """Write a booktabs LaTeX table; bold the best value in each column.

    ``df_disp`` holds numeric values (index = algorithms, columns = metrics).
    ``higher_better`` maps column -> bool; a column absent from it is not bolded.
    """
    higher_better = higher_better or {}
    cols = list(df_disp.columns)
    best = {}
    for c in cols:
        col = df_disp[c]
        if c in higher_better and col.notna().any():
            best[c] = col.idxmax() if higher_better[c] else col.idxmin()
        else:
            best[c] = None

    lines = [
        "% Auto-generated by scripts/compare_eda_cluster.py",
        "\\begin{table}[t]", "\\centering",
        "\\setlength{\\tabcolsep}{10pt}",
        "\\begin{tabular}{l" + "r" * len(cols) + "}",
        "\\toprule",
        index_name + " & " + " & ".join(cols) + " \\\\",
        "\\midrule",
    ]
    for idx in df_disp.index:
        cells = []
        for c in cols:
            v = df_disp.loc[idx, c]
            s = _fmt(v, prec)
            if best[c] == idx and s != "--":
                s = "$\\mathbf{" + s + "}$"
            cells.append(s)
        lines.append(pretty(idx) + " & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    if note:
        lines.append("\\\\[2pt]\\footnotesize " + note)
    lines += [f"\\caption{{{caption}}}", f"\\label{{{label}}}", "\\end{table}", ""]
    with open(path, "w") as fh:
        fh.write("\n".join(lines))


def latex_table_meanstd(mean_df, std_df, path, caption, label, higher_better,
                        prec=3, index_name="Algorithm", note=None):
    """LaTeX table of ``mean ± std`` cells; bold the best mean per column."""
    cols = list(mean_df.columns)
    best = {}
    for c in cols:
        col = mean_df[c]
        best[c] = (col.idxmax() if higher_better.get(c, True) else col.idxmin()) \
            if col.notna().any() else None
    lines = [
        "% Auto-generated by scripts/compare_eda_cluster.py",
        "\\begin{table}[t]", "\\centering",
        "\\setlength{\\tabcolsep}{8pt}",
        "\\begin{tabular}{l" + "r" * len(cols) + "}",
        "\\toprule",
        index_name + " & " + " & ".join(cols) + " \\\\",
        "\\midrule",
    ]
    for idx in mean_df.index:
        cells = []
        for c in cols:
            mu = mean_df.loc[idx, c]
            sd = std_df.loc[idx, c] if std_df is not None else np.nan
            if mu is None or np.isnan(mu):
                cells.append("--"); continue
            body = _fmt(mu, prec)
            if best[c] == idx:
                body = "\\mathbf{" + body + "}"
            cell = "$" + body + "$"
            if std_df is not None and not np.isnan(sd):
                cell = "$" + body + "{\\scriptstyle\\pm" + _fmt(sd, prec) + "}$"
            cells.append(cell)
        lines.append(pretty(idx) + " & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    if note:
        lines.append("\\\\[2pt]\\footnotesize " + note)
    lines += [f"\\caption{{{caption}}}", f"\\label{{{label}}}", "\\end{table}", ""]
    with open(path, "w") as fh:
        fh.write("\n".join(lines))


# ---------------------------------------------------------------------------
# Aggregation helpers
# ---------------------------------------------------------------------------

def _nanmean(s):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return np.nanmean(s.values.astype(float)) if len(s) else np.nan


def _nanstd(s):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return np.nanstd(s.values.astype(float)) if len(s) else np.nan


def problem_algo_matrix(df, metric, algos, subset=None):
    """(problem x algorithm) matrix of the per-problem MEAN of *metric*.

    Each problem is a block: the value is averaged over temperatures and train
    splits.  Rows with any missing algorithm (incomplete block) are dropped so
    the matrix supports paired/blocked statistics (Friedman, average ranks).
    """
    d = df if subset is None else df[subset]
    piv = d.pivot_table(index="problem", columns="algorithm", values=metric,
                        aggfunc="mean")
    piv = piv.reindex(columns=[a for a in algos if a in piv.columns])
    return piv.dropna(axis=0, how="any")


def average_ranks(matrix, higher_better=True):
    """Average rank per algorithm across problems (1 = best)."""
    ranks = matrix.rank(axis=1, ascending=not higher_better)
    return ranks.mean(axis=0)


def macro_mean(matrix):
    """Mean over problems of the per-problem means (each problem weighted equally)."""
    return matrix.mean(axis=0)


def macro_by(df, metric, algos, mask=None):
    """Series algo -> macro-mean of *metric* (per-problem mean, then mean over
    problems; each problem weighted equally, NaNs skipped).

    Unlike :func:`problem_algo_matrix` this does *not* require complete blocks,
    so it is used for the descriptive per-group/family/temperature tables where
    a cell may be missing for a few problems.  Using the same macro-average
    everywhere keeps a given "$\\rho$" value identical across all tables/figures.
    """
    d = df if mask is None else df[mask]
    piv = d.pivot_table(index="problem", columns="algorithm", values=metric,
                        aggfunc="mean")
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        out = piv.mean(axis=0, skipna=True)
    return out.reindex(algos)


def temp_labels(df):
    """Ordered (float, label) list of the temperatures present in *df*."""
    fmt = lambda t: ("%g" % t)
    ts = sorted(df["temperature"].dropna().unique())
    return [(t, fmt(t)) for t in ts]


# ---------------------------------------------------------------------------
# 1. Main ranking (priority: test Spearman correlation, blocked by problem)
# ---------------------------------------------------------------------------

def main_ranking(df, algos, tdir, fdir):
    # Block by problem: pooled means are dominated by problem difficulty
    # (per-problem rho ranges from ~0 to ~1), so we rank algorithms by their
    # AVERAGE RANK on the per-problem test correlation (Demsar 2006).
    Mtest = problem_algo_matrix(df, "test_sp", algos)
    Mtrain = problem_algo_matrix(df, "train_sp", algos)
    Mf1 = problem_algo_matrix(df, "f1", algos)
    Mtime = problem_algo_matrix(df, "time", algos)
    n_problems = Mtest.shape[0]

    rank_test = average_ranks(Mtest, higher_better=True)
    order = list(rank_test.sort_values().index)      # ascending rank = best first

    # Displayed values use the all-problem macro-mean (so a given rho matches
    # the per-group/family tables); ranks use the complete-case matrix above.
    disp = pd.DataFrame(index=order)
    disp["Rank"] = rank_test.reindex(order)
    disp["Test $\\rho$"] = macro_by(df, "test_sp", algos).reindex(order)
    disp["Train $\\rho$"] = macro_by(df, "train_sp", algos).reindex(order)
    disp["F1"] = macro_by(df, "f1", algos).reindex(order)
    disp["Time (s)"] = macro_by(df, "time", algos).reindex(order)
    higher = {"Rank": False, "Test $\\rho$": True, "Train $\\rho$": True,
              "F1": True, "Time (s)": False}
    latex_table(
        disp, os.path.join(tdir, "table_main_ranking.tex"),
        "BN learning algorithms ranked by their average rank on the "
        "test-regime Spearman correlation $\\rho$ (blocked by problem; "
        f"1 = best, averaged over {n_problems} problems). Macro-averaged "
        "test/train $\\rho$, skeleton F1 and learning time are shown for "
        "reference. Correlation is the priority metric.",
        "tab:eda_main_ranking", higher_better=higher, prec=3)

    # figure: horizontal bar of macro-mean test rho ordered by average rank,
    # with the train-regime value overlaid.
    fig, ax = plt.subplots(figsize=(7.8, 8))
    y = np.arange(len(order))[::-1]
    test_mu = disp["Test $\\rho$"].values
    train_mu = disp["Train $\\rho$"].values
    ax.barh(y + 0.22, test_mu, height=0.42, color="#2a78d6",
            label="Test (held-out regimes)")
    ax.barh(y - 0.22, train_mu, height=0.42, color="#eda100", alpha=0.95,
            label="Train regime")
    xmax = float(np.nanmax(np.concatenate([test_mu, train_mu])))
    for yi, a in zip(y, order):
        bar_end = max(test_mu[list(order).index(a)], train_mu[list(order).index(a)])
        ax.text(bar_end + 0.008, yi, f"rank {disp.loc[a, 'Rank']:.1f}",
                ha="left", va="center", fontsize=9, color="#444")
    ax.set_xlim(0, xmax * 1.22)
    ax.set_yticks(y)
    ax.set_yticklabels([pretty(a) for a in order])
    ax.set_xlabel(r"Macro-mean Spearman $\rho$ (predicted vs. target prob.)")
    ax.axvline(0, color="k", lw=0.8)
    ax.legend(loc="lower right")
    fig.savefig(os.path.join(fdir, "fig_ranking_bar.pdf"))
    plt.close(fig)
    return order, Mtest


# ---------------------------------------------------------------------------
# 2. Train vs test generalisation
# ---------------------------------------------------------------------------

def train_vs_test(df, algos, order, tdir, fdir):
    tr_s = macro_by(df, "train_sp", algos)
    te_s = macro_by(df, "test_sp", algos)
    disp = pd.DataFrame({"Train $\\rho$": tr_s, "Test $\\rho$": te_s,
                         "Gap": tr_s - te_s}).loc[order]
    latex_table(disp, os.path.join(tdir, "table_train_vs_test.tex"),
                "Generalisation from the training regime to the two held-out "
                "regimes: macro-mean train and test Spearman $\\rho$ and their "
                "gap (train$-$test). A small gap indicates a model whose "
                "probability ordering transfers across selection-pressure regimes.",
                "tab:eda_train_vs_test",
                higher_better={"Train $\\rho$": True, "Test $\\rho$": True,
                               "Gap": False}, prec=3)

    # scatter train vs test
    fig, ax = plt.subplots(figsize=(7, 7))
    for a in algos:
        x, y = tr_s[a], te_s[a]
        ax.scatter(x, y, s=45, color="#2a78d6", zorder=3)
        ax.annotate(pretty(a), (x, y), fontsize=10, xytext=(3, 3),
                    textcoords="offset points")
    lim = [min(0.0, float(np.nanmin(te_s.values))), 1.0]
    ax.plot(lim, lim, "--", color="grey", lw=1)
    ax.set_xlabel(r"Train-regime $\rho$")
    ax.set_ylabel(r"Test-regime $\rho$ (held-out)")
    ax.set_xlim(lim); ax.set_ylim(lim)
    fig.savefig(os.path.join(fdir, "fig_train_vs_test.pdf"))
    plt.close(fig)


# ---------------------------------------------------------------------------
# 3. 3x3 generalisation matrix (train split -> eval split)
# ---------------------------------------------------------------------------

def generalisation_matrix(df, fdir, tdir):
    # raw per-split correlations tied to the training split
    M = np.full((3, 3), np.nan)
    for i in range(3):                        # train split
        sub = df[df.train_set == i]
        for j in range(3):                    # eval split
            M[i, j] = _nanmean(sub[f"sp_s{j}"])
    fig, ax = plt.subplots(figsize=(6.2, 5.4))
    im = ax.imshow(M, cmap="viridis", vmin=np.nanmin(M), vmax=np.nanmax(M))
    for i in range(3):
        for j in range(3):
            ax.text(j, i, f"{M[i, j]:.3f}", ha="center", va="center",
                    color="white" if M[i, j] < (np.nanmin(M)+np.nanmax(M))/2 else "black",
                    fontsize=14, fontweight="bold" if i == j else "normal")
    ax.set_xticks(range(3)); ax.set_yticks(range(3))
    ax.set_xticklabels(["split 0", "split 1", "split 2"])
    ax.set_yticklabels(["split 0", "split 1", "split 2"])
    ax.set_xlabel("Evaluation regime")
    ax.set_ylabel("Training regime")
    ax.grid(False)
    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04, label=r"mean $\rho$")
    fig.savefig(os.path.join(fdir, "fig_generalisation_matrix.pdf"))
    plt.close(fig)

    # small LaTeX companion
    dfm = pd.DataFrame(M, index=["split 0", "split 1", "split 2"],
                       columns=["split 0", "split 1", "split 2"])
    latex_table(dfm, os.path.join(tdir, "table_generalisation_matrix.tex"),
                "Mean Spearman $\\rho$ by training regime (row) and evaluation "
                "regime (column), averaged over all algorithms, problems and "
                "temperatures. Diagonal = train; off-diagonal = the held-out "
                "test regimes.", "tab:eda_genmatrix",
                higher_better={c: True for c in dfm.columns}, prec=3,
                index_name="Train\\,$\\backslash$\\,Eval")


# ---------------------------------------------------------------------------
# 4. By problem-size group
# ---------------------------------------------------------------------------

def by_group(df, algos, order, tdir, fdir):
    groups = [g for g in GROUP_ORDER if g in df.group.unique()]
    mu = pd.DataFrame(index=order, columns=[g.capitalize() for g in groups], dtype=float)
    for g in groups:
        s = macro_by(df, "test_sp", order, mask=(df.group == g))
        mu[g.capitalize()] = s.reindex(order)
    latex_table(mu, os.path.join(tdir, "table_by_group.tex"),
                "Macro-mean test-regime Spearman $\\rho$ by problem-size group "
                "(Small $n<50$, Medium $50\\le n<100$, Large $n\\ge100$).",
                "tab:eda_by_group",
                higher_better={c: True for c in mu.columns}, prec=3)

    fig, ax = plt.subplots(figsize=(11, 6))
    x = np.arange(len(order))
    w = 0.26
    colors = {"Small": "#1baf7a", "Medium": "#2a78d6", "Large": "#e34948"}
    for k, g in enumerate([g.capitalize() for g in groups]):
        ax.bar(x + (k - 1) * w, mu[g].values, width=w, label=g,
               color=colors.get(g, None))
    ax.set_xticks(x); ax.set_xticklabels([pretty(a) for a in order], rotation=60, ha="right")
    ax.set_ylabel(r"Test-regime $\rho$")
    ax.axhline(0, color="k", lw=0.8)
    ax.legend(title="Problem size")
    fig.savefig(os.path.join(fdir, "fig_by_group.pdf"))
    plt.close(fig)


# ---------------------------------------------------------------------------
# 5. By problem family (heatmap + table)
# ---------------------------------------------------------------------------

def by_family(df, algos, order, tdir, fdir):
    fams = sorted(df.family.unique())
    mu = pd.DataFrame(index=order, columns=fams, dtype=float)
    for fam in fams:
        s = macro_by(df, "test_sp", order, mask=(df.family == fam))
        mu[fam] = s.reindex(order)
    latex_table(mu, os.path.join(tdir, "table_by_family.tex"),
                "Macro-mean test-regime Spearman $\\rho$ per problem family. Best "
                "algorithm per family in bold.", "tab:eda_by_family",
                higher_better={c: True for c in mu.columns}, prec=3)

    fig, ax = plt.subplots(figsize=(1.0 + 0.75 * len(fams), 0.42 * len(order) + 1.5))
    data = mu.values.astype(float)
    im = ax.imshow(data, aspect="auto", cmap="RdYlGn",
                   vmin=np.nanmin(data), vmax=np.nanmax(data))
    ax.set_xticks(range(len(fams))); ax.set_xticklabels(fams, rotation=45, ha="right")
    ax.set_yticks(range(len(order))); ax.set_yticklabels([pretty(a) for a in order])
    for i in range(len(order)):
        for j in range(len(fams)):
            val = data[i, j]
            if not np.isnan(val):
                ax.text(j, i, f"{val:.2f}", ha="center", va="center", fontsize=8,
                        color="black")
    ax.grid(False)
    fig.colorbar(im, ax=ax, fraction=0.03, pad=0.02, label=r"test $\rho$")
    fig.savefig(os.path.join(fdir, "fig_family_heatmap.pdf"))
    plt.close(fig)


# ---------------------------------------------------------------------------
# 6. By temperature
# ---------------------------------------------------------------------------

def by_temperature(df, algos, order, tdir, fdir):
    temps = temp_labels(df)                    # [(float, "0.1"), (1.0,"1"), (10.0,"10")]
    mu = pd.DataFrame(index=order, columns=[f"T={lab}" for _, lab in temps], dtype=float)
    for tval, lab in temps:
        s = macro_by(df, "test_sp", order, mask=(df.temperature == tval))
        mu[f"T={lab}"] = s.reindex(order)
    latex_table(mu, os.path.join(tdir, "table_by_temperature.tex"),
                "Macro-mean test-regime Spearman $\\rho$ per Boltzmann "
                "temperature $T$ (higher $T$ = flatter target distribution).",
                "tab:eda_by_temperature",
                higher_better={c: True for c in mu.columns}, prec=3)

    fig, ax = plt.subplots(figsize=(8, 6))
    top = order[:8]
    xs = [tval for tval, _ in temps]
    for a in top:
        ys = [macro_by(df, "test_sp", [a], mask=(df.temperature == tval))[a]
              for tval, _ in temps]
        ax.plot(xs, ys, "-o", label=pretty(a), lw=2, ms=6)
    ax.set_xscale("log")
    ax.set_xlabel("Boltzmann temperature $T$")
    ax.set_ylabel(r"Test-regime $\rho$")
    ax.set_xticks(xs); ax.set_xticklabels([lab for _, lab in temps])
    ax.legend(ncol=2, fontsize=11)
    fig.savefig(os.path.join(fdir, "fig_by_temperature.pdf"))
    plt.close(fig)


# ---------------------------------------------------------------------------
# 7. Distribution + structure-vs-correlation
# ---------------------------------------------------------------------------

def distributions(df, algos, order, fdir):
    # boxplot of test rho per algorithm (sorted by median)
    data = [df[df.algorithm == a].test_sp.dropna().values for a in order]
    fig, ax = plt.subplots(figsize=(11, 6))
    bp = ax.boxplot(data, vert=True, patch_artist=True, showfliers=False,
                    medianprops=dict(color="black"))
    for patch in bp["boxes"]:
        patch.set_facecolor("#2a78d6"); patch.set_alpha(0.7)
    ax.set_xticklabels([pretty(a) for a in order], rotation=60, ha="right")
    ax.set_ylabel(r"Test-regime $\rho$")
    ax.axhline(0, color="k", lw=0.8)
    fig.savefig(os.path.join(fdir, "fig_corr_boxplot.pdf"))
    plt.close(fig)

    # F1 vs test rho (macro-mean per algorithm)
    f1_s = macro_by(df, "f1", algos)
    te_s = macro_by(df, "test_sp", algos)
    fig, ax = plt.subplots(figsize=(7, 6.5))
    for a in algos:
        ax.scatter(f1_s[a], te_s[a], s=45, color="#4a3aa7", zorder=3)
        ax.annotate(pretty(a), (f1_s[a], te_s[a]), fontsize=10, xytext=(3, 3),
                    textcoords="offset points")
    ax.set_xlabel("Macro-mean skeleton F1")
    ax.set_ylabel(r"Macro-mean test-regime $\rho$")
    fig.savefig(os.path.join(fdir, "fig_f1_vs_corr.pdf"))
    plt.close(fig)


# ---------------------------------------------------------------------------
# 8. Statistics: Friedman + Nemenyi on per-problem test correlation
# ---------------------------------------------------------------------------

def _nemenyi_cd(k, n, alpha=0.05):
    """Nemenyi critical difference for k algorithms over n blocks (alpha=0.05)."""
    # studentised-range-based q_alpha / sqrt(2) values (Demsar 2006, Table 5)
    q05 = {2: 1.960, 3: 2.343, 4: 2.569, 5: 2.728, 6: 2.850, 7: 2.949,
           8: 3.031, 9: 3.102, 10: 3.164, 11: 3.219, 12: 3.268, 13: 3.313,
           14: 3.354, 15: 3.391, 16: 3.426, 17: 3.458, 18: 3.489, 19: 3.518,
           20: 3.547}
    q = q05.get(k, 3.547)
    return q * np.sqrt(k * (k + 1) / (6.0 * n))


def statistics(df, algos, order, Mtest, tdir, fdir):
    """Friedman omnibus test + Nemenyi post-hoc on the per-problem matrix."""
    from scipy.stats import friedmanchisquare
    k, n = Mtest.shape[1], Mtest.shape[0]
    cols = list(Mtest.columns)
    txt = []

    stat, p = friedmanchisquare(*[Mtest[c].values for c in cols])
    txt.append(f"Friedman test on per-problem test rho over {n} problems, "
               f"{k} algorithms: chi2={stat:.1f}, p={p:.2e} "
               f"({'significant' if p < 0.05 else 'not significant'} at 0.05).")

    ranks = Mtest.rank(axis=1, ascending=False).mean(axis=0)   # 1 = best
    ranks = ranks.reindex(order)
    cd = _nemenyi_cd(k, n)
    txt.append(f"Nemenyi critical difference (alpha=0.05): CD={cd:.2f} rank units.")
    best = order[0]
    tied = [a for a in order[1:] if (ranks[a] - ranks[best]) <= cd]
    txt.append(f"Best by average rank: {pretty(best)} ({ranks[best]:.2f}). "
               f"Within one CD of the best (statistically comparable): "
               f"{', '.join(pretty(a) for a in tied) or '(none)'}.")

    # --- critical-difference point plot (average rank +/- CD/2 reference) ----
    fig, ax = plt.subplots(figsize=(8, 8))
    yy = np.arange(len(order))[::-1]
    rv = [ranks[a] for a in order]
    ax.errorbar(rv, yy, xerr=cd / 2, fmt="o", color="#2a78d6", ms=7,
                elinewidth=2, capsize=4)
    # shade the "tied with best" band
    ax.axvspan(ranks[best], ranks[best] + cd, color="#1baf7a", alpha=0.12,
               label=f"within CD of best (CD={cd:.2f})")
    ax.axvline(ranks[best], color="#1baf7a", lw=1.2, ls="--")
    ax.set_yticks(yy); ax.set_yticklabels([pretty(a) for a in order])
    ax.set_xlabel("Average rank (1 = best)   [error bar = CD/2]")
    ax.legend(loc="lower right", fontsize=11)
    ax.invert_xaxis()                       # best (low rank) on the right
    fig.savefig(os.path.join(fdir, "fig_avg_rank_cd.pdf"))
    plt.close(fig)

    # --- Nemenyi significance heatmap among the top-10 ----------------------
    if _HAVE_DUNN:
        pv = sp_posthoc.posthoc_nemenyi_friedman(Mtest.values)
        pv.index = cols; pv.columns = cols
        top = order[:min(10, len(order))]
        sub = pv.loc[top, top].astype(float)
        fig, ax = plt.subplots(figsize=(8, 7))
        im = ax.imshow(sub.values, cmap="RdYlGn", vmin=0, vmax=0.2)
        for i in range(len(top)):
            for j in range(len(top)):
                v = sub.values[i, j]
                ax.text(j, i, "--" if i == j else f"{v:.2f}", ha="center",
                        va="center", fontsize=9,
                        color="black")
        ax.set_xticks(range(len(top))); ax.set_xticklabels([pretty(a) for a in top], rotation=45, ha="right")
        ax.set_yticks(range(len(top))); ax.set_yticklabels([pretty(a) for a in top])
        ax.grid(False)
        fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04, label="Nemenyi $p$")
        fig.savefig(os.path.join(fdir, "fig_nemenyi_heatmap.pdf"))
        plt.close(fig)
        txt.append("Nemenyi pairwise p-values written to fig_nemenyi_heatmap.pdf "
                   "(green = p>0.05, i.e. statistically comparable).")

    with open(os.path.join(tdir, "stats_summary.txt"), "w") as fh:
        fh.write("\n".join(txt) + "\n")
    print("\n".join(txt))


# ---------------------------------------------------------------------------
# 9. Best algorithm per optimization problem (priority: test correlation)
# ---------------------------------------------------------------------------

def best_per_problem(df, algos, tdir, fdir):
    """Which algorithm wins each problem / family by test-split Spearman rho."""
    # per-problem mean test rho and F1 (over temperatures and train splits)
    Msp = df.pivot_table(index="problem", columns="algorithm", values="test_sp",
                         aggfunc="mean").reindex(columns=algos)
    Mf1 = df.pivot_table(index="problem", columns="algorithm", values="f1",
                         aggfunc="mean").reindex(columns=algos)
    meta = df.drop_duplicates("problem").set_index("problem")[["family", "n", "group"]]

    recs = []
    for prob in Msp.index:
        row = Msp.loc[prob].dropna()
        if row.empty:
            continue
        s = row.sort_values(ascending=False)
        best, second = s.index[0], (s.index[1] if len(s) > 1 else None)
        recs.append({
            "problem": prob, "family": meta.loc[prob, "family"],
            "n": int(meta.loc[prob, "n"]), "group": meta.loc[prob, "group"],
            "best": best, "rho": float(s.iloc[0]),
            "best_f1": float(Mf1.loc[prob, best]) if not np.isnan(Mf1.loc[prob, best]) else np.nan,
            "second": second, "rho2": float(s.iloc[1]) if len(s) > 1 else np.nan,
        })
    bp = pd.DataFrame(recs)
    bp = bp.sort_values(["group", "family", "n"],
                        key=lambda c: c.map({"small": 0, "medium": 1, "large": 2}) if c.name == "group" else c)

    # ---- LaTeX table: best per problem -----------------------------------
    lines = [
        "% Auto-generated by scripts/compare_eda_cluster.py",
        "\\begin{table}[t]", "\\centering", "\\setlength{\\tabcolsep}{8pt}",
        "\\begin{tabular}{llrrrlr}", "\\toprule",
        "Problem & $n$ & Best (by $\\rho$) & Test $\\rho$ & F1 & Runner-up & $\\rho$ \\\\",
        "\\midrule",
    ]
    cur = None
    for _, r in bp.iterrows():
        if r["group"] != cur:
            cur = r["group"]
            lines.append("\\midrule" if lines[-1] != "\\midrule" else "")
            lines.append("\\multicolumn{7}{l}{\\textit{" + cur.capitalize()
                         + "}} \\\\")
        second = pretty(r["second"]) if r["second"] else "--"
        rho2 = _fmt(r["rho2"]) if not np.isnan(r["rho2"]) else "--"
        lines.append(
            f"{r['family']}\\_{r['n']} & {r['n']} & "
            f"\\textbf{{{pretty(r['best'])}}} & {_fmt(r['rho'])} & "
            f"{_fmt(r['best_f1'])} & {second} & {rho2} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}",
              "\\caption{Best BN learning algorithm on each optimization problem, "
              "by mean test-split Spearman correlation $\\rho$ (higher is better). "
              "F1 is the winner's skeleton F1; the runner-up and its $\\rho$ are "
              "shown for context.}",
              "\\label{tab:eda_best_per_problem}", "\\end{table}", ""]
    with open(os.path.join(tdir, "table_best_per_problem.tex"), "w") as fh:
        fh.write("\n".join(l for l in lines if l != ""))

    # ---- LaTeX table: best per family ------------------------------------
    fam_rows = []
    for fam, sub in bp.groupby("family"):
        # winner per family = algorithm with the highest mean test rho over the
        # family's problems
        fam_mask = df.family == fam
        s = macro_by(df, "test_sp", algos, mask=fam_mask).dropna().sort_values(ascending=False)
        n_wins = int((sub["best"] == s.index[0]).sum())
        fam_rows.append({"Family": fam, "Best": pretty(s.index[0]),
                         "rho": float(s.iloc[0]),
                         "2nd": pretty(s.index[1]) if len(s) > 1 else "--",
                         "won": f"{n_wins}/{len(sub)}"})
    famdf = pd.DataFrame(fam_rows).set_index("Family")
    # write manually to keep the string columns
    rho_h = "Test $\\rho$"
    flines = ["% Auto-generated by scripts/compare_eda_cluster.py",
              "\\begin{table}[t]", "\\centering", "\\setlength{\\tabcolsep}{10pt}",
              "\\begin{tabular}{llrlc}", "\\toprule",
              "Family & Best & " + rho_h + " & 2nd & Instances won \\\\", "\\midrule"]
    for fam, r in famdf.iterrows():
        best_b = "\\textbf{" + str(r["Best"]) + "}"
        flines.append(fam + " & " + best_b + " & " + _fmt(r["rho"]) + " & "
                      + str(r["2nd"]) + " & " + str(r["won"]) + " \\\\")
    flines += ["\\bottomrule", "\\end{tabular}",
               "\\caption{Best algorithm per problem family by macro-mean "
               "test-split Spearman $\\rho$. `Instances won' counts the family's "
               "size instances on which that algorithm is also the per-instance "
               "winner.}", "\\label{tab:eda_best_per_family}", "\\end{table}", ""]
    with open(os.path.join(tdir, "table_best_per_family.tex"), "w") as fh:
        fh.write("\n".join(flines))

    # ---- Figure: per-problem best rho, coloured by winning algorithm ------
    winners = list(dict.fromkeys(bp["best"].tolist()))       # stable unique
    cmap = plt.get_cmap("tab20")
    wcolor = {w: cmap(i % 20) for i, w in enumerate(winners)}
    bpf = bp.sort_values("rho", ascending=True)
    fig, ax = plt.subplots(figsize=(9, 0.32 * len(bpf) + 1.2))
    y = np.arange(len(bpf))
    ax.barh(y, bpf["rho"].values,
            color=[wcolor[w] for w in bpf["best"]], edgecolor="white")
    ax.set_yticks(y)
    ax.set_yticklabels([f"{f}\\_{n}".replace("\\_", "_")
                        for f, n in zip(bpf["family"], bpf["n"])], fontsize=9)
    for yi, (rho, w) in enumerate(zip(bpf["rho"], bpf["best"])):
        ax.text(rho + 0.005, yi, pretty(w), va="center", fontsize=8,
                color=wcolor[w])
    ax.set_xlabel(r"Best test-regime Spearman $\rho$ (winner labelled)")
    ax.set_xlim(min(0, bpf["rho"].min()), 1.05)
    handles = [plt.Rectangle((0, 0), 1, 1, color=wcolor[w]) for w in winners]
    ax.legend(handles, [pretty(w) for w in winners], title="Winning algorithm",
              ncol=2, fontsize=10, loc="lower right")
    fig.savefig(os.path.join(fdir, "fig_best_per_problem.pdf"))
    plt.close(fig)

    # ---- Figure: number of problems won per algorithm --------------------
    counts = bp["best"].value_counts()
    fig, ax = plt.subplots(figsize=(8, 5))
    algs = counts.index.tolist()
    ax.bar([pretty(a) for a in algs], counts.values, color="#2a78d6")
    for i, v in enumerate(counts.values):
        ax.text(i, v + 0.1, str(int(v)), ha="center", fontsize=11)
    ax.set_ylabel("Problems won (of %d)" % len(bp))
    ax.set_xticklabels([pretty(a) for a in algs], rotation=40, ha="right")
    fig.savefig(os.path.join(fdir, "fig_win_counts.pdf"))
    plt.close(fig)

    print("Wins per algorithm (by test rho):",
          ", ".join(f"{pretty(a)}={c}" for a, c in counts.items()))


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    csv_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(_ROOT, "results", "eda_cluster_results.csv")
    out_dir = sys.argv[2] if len(sys.argv) > 2 else os.path.join(_ROOT, "results", "eda_cluster_analysis")
    tdir = os.path.join(out_dir, "tables")
    fdir = os.path.join(out_dir, "figures")
    os.makedirs(tdir, exist_ok=True)
    os.makedirs(fdir, exist_ok=True)

    df = pd.read_csv(csv_path)
    df["temp_str"] = df["temp_str"].astype(str)
    algos = [a for a in PRETTY if a in df.algorithm.unique()]
    algos += [a for a in df.algorithm.unique() if a not in algos]
    print(f"Loaded {len(df)} rows, {len(algos)} algorithms, "
          f"{df.problem.nunique()} problems.")

    order, Mtest = main_ranking(df, algos, tdir, fdir)
    print("Ranking by average rank (test rho):",
          " > ".join(pretty(a) for a in order[:6]), "...")
    train_vs_test(df, algos, order, tdir, fdir)
    generalisation_matrix(df, fdir, tdir)
    by_group(df, algos, order, tdir, fdir)
    by_family(df, algos, order, tdir, fdir)
    by_temperature(df, algos, order, tdir, fdir)
    distributions(df, algos, order, fdir)
    best_per_problem(df, algos, tdir, fdir)
    statistics(df, algos, order, Mtest, tdir, fdir)

    n_tab = len([f for f in os.listdir(tdir) if f.endswith(".tex")])
    n_fig = len([f for f in os.listdir(fdir) if f.endswith(".pdf")])
    print(f"\nWrote {n_tab} LaTeX tables -> {tdir}")
    print(f"Wrote {n_fig} figures      -> {fdir}")


if __name__ == "__main__":
    main()
