"""
Int_FDA (Tree-based Factorized Distribution Algorithm for Integers) — sampling

This is the *generation* half of Int_FDA; the model is produced by
:class:`~pateda.learning.int_fda.LearnIntFDA`.  See that module for the full
description of the algorithm and its auxiliary tables.

Generation algorithm (Santana, Ochoa & Soto, 2002)
--------------------------------------------------
No probability table is ever consulted.  Each new individual is built by
walking the tree from the root down and *copying genes from donor vectors of
the selected population*:

1. **Root.**  Pick a uniformly random vector of the selected set and copy its
   value for the root variable.  (This reproduces the empirical marginal of the
   root.)

2. **Child ``X_j`` of an already-instantiated parent ``X_i = v``.**  All selected
   vectors whose parent equals ``v`` occupy a contiguous block of column ``i``
   of ``PopulValues``, namely rows ``[ParentIndices[i][v], ParentIndices[i][v+1])``.
   Pick a uniformly random row ``r`` in that block, read the donor index
   ``d = PopulValues[r, i]``, and copy ``X_j = S[d, j]``.  (This reproduces the
   empirical conditional ``p(X_j | X_i = v)`` of the selected set.)

Because every value assigned to a parent was itself copied from a real selected
vector, that value is always present in the selected set, so the block for a
child is never empty and generation never fails.

The distribution sampled this way is *exactly* the Chow-Liu tree distribution
of the selected set — the same distribution a Tree-EDA would define — but it is
obtained without materializing any ``c × c`` conditional table, which is what
makes Int_FDA suitable for very high cardinality.

The implementation is vectorized across the requested number of samples: each
tree edge is processed once for the whole new population, mirroring the way
:class:`~pateda.sampling.fda.SampleFDA` iterates over cliques.

References
----------
- Santana, R., Ochoa, A., & Soto, M. R. (2002). "Solving problems with integer
  representation using a tree based Factorized Distribution Algorithm."
  ICIMAF, Havana, Cuba.
"""

from typing import Any, List, Optional
import numpy as np

from pateda.core.components import SamplingMethod
from pateda.core.models import Model


class SampleIntFDA(SamplingMethod):
    """
    Sample a new population from an Int_FDA model.

    Consumes the model produced by
    :class:`~pateda.learning.int_fda.LearnIntFDA`: the tree (``structure``) and
    the ``selected_population`` / ``popul_values`` / ``parent_indices`` tables
    (``parameters``).  New individuals are generated by donor-copying along the
    tree; no probability table is used.

    Diversity
    ---------
    Pure donor-copying is *closed* under the selected set: it can only reproduce
    values (and parent/child value-pairs) that already occur in the selected
    population.  At high cardinality this limits exploration.  Two independent,
    composable ways to inject values that are **not** in the base population are
    available:

    - **In-sampling novelty** (``novelty_prob`` > 0): with that per-gene
      probability a variable is drawn uniformly from ``[0, cardinality)`` rather
      than copied from a donor.  Because it is applied while the tree is walked,
      a novelty at a parent simply leaves its children with an empty conditional
      block, which the sampler already handles by falling back to a uniform
      donor — so generation stays well defined.  This behaves like a
      Laplace/smoothing term on the implicit conditionals.
    - **Post-sampling mutation**: any :class:`~pateda.core.components.MutationMethod`
      plugged into the EDA (e.g.
      :class:`~pateda.mutation.random_reset.RandomResetMutation` for integers)
      is applied by the EDA loop to the whole population *after* sampling, and is
      fully decoupled from the tree.

    Both preserve Int_FDA's ``O(N·n + c·n)`` memory profile.
    """

    def __init__(self, n_samples: int, novelty_prob: float = 0.0):
        """
        Initialize Int_FDA sampling.

        Args:
            n_samples: Number of individuals to generate.
            novelty_prob: Per-gene probability of *diversity injection*.  With
                probability ``novelty_prob`` a variable is drawn uniformly at
                random from its full range ``[0, cardinality)`` instead of being
                copied from a donor of the selected set.  This is what lets
                Int_FDA emit values that are **not** present in the base
                population (see the class docstring).  ``0.0`` (default)
                recovers the pure donor-copy algorithm of the paper.  It acts
                like a Laplace/smoothing term on the implicit conditional
                distribution and is analogous to a random-reset mutation folded
                into the generation step.
        """
        if not 0.0 <= novelty_prob <= 1.0:
            raise ValueError(
                f"novelty_prob must be in [0, 1], got {novelty_prob}"
            )
        self.n_samples = n_samples
        self.novelty_prob = novelty_prob

    def sample(
        self,
        n_vars: int,
        model: Model,
        cardinality: np.ndarray,
        aux_pop: Optional[np.ndarray] = None,
        aux_fitness: Optional[np.ndarray] = None,
        rng: Optional[np.random.Generator] = None,
        **params: Any,
    ) -> np.ndarray:
        """
        Generate a new population from the Int_FDA model.

        Args:
            n_vars: Number of variables.
            model: Int_FDA model (see :class:`~pateda.learning.int_fda.LearnIntFDA`).
            cardinality: Variable cardinalities (unused; bounds are baked into
                the model's index tables).
            aux_pop: Unused — Int_FDA carries the selected population inside the
                model, so it does not depend on the auxiliary population passed
                by the EDA loop.
            aux_fitness: Unused.
            rng: Random number generator (None creates a fresh one).
            **params: Additional parameters.  ``n_samples`` overrides the
                instance value.

        Returns:
            Sampled population of shape ``(n_samples, n_vars)``.
        """
        if rng is None:
            rng = np.random.default_rng()

        params_dict = model.parameters
        if not isinstance(params_dict, dict) or "selected_population" not in params_dict:
            raise TypeError(
                "SampleIntFDA expects an Int_FDA model produced by LearnIntFDA "
                "(parameters must contain 'selected_population', 'popul_values' "
                "and 'parent_indices')."
            )

        n_samples = int(params.get("n_samples", self.n_samples))
        novelty_prob = float(params.get("novelty_prob", self.novelty_prob))
        cardinality = np.asarray(cardinality)

        cliques = model.structure
        selected = params_dict["selected_population"]
        popul_values = params_dict["popul_values"]
        parent_indices: List[np.ndarray] = params_dict["parent_indices"]

        n_selected = selected.shape[0]

        # New population, -1 marks not-yet-assigned (used for a final sanity check).
        new_pop = -np.ones((n_samples, n_vars), dtype=int)

        def inject_novelty(var: int) -> None:
            """Diversity injection: overwrite the donor-copied value of ``var``
            with a uniform random value in ``[0, cardinality[var])`` for a random
            ``novelty_prob`` fraction of individuals.  This is the *only* route by
            which Int_FDA can emit a value absent from the selected set."""
            if novelty_prob <= 0.0:
                return
            novel = rng.random(n_samples) < novelty_prob
            n_novel = int(novel.sum())
            if n_novel:
                new_pop[novel, var] = rng.integers(
                    0, int(cardinality[var]), size=n_novel
                )

        # Cliques are ordered so a parent is always processed before its
        # children (topological order guaranteed by the spanning-tree build).
        for c in range(cliques.shape[0]):
            n_parents = int(cliques[c, 0])

            if n_parents == 0:
                # Root (or isolated node): copy the variable from a random donor.
                root_var = int(cliques[c, 2])
                donors = rng.integers(0, n_selected, size=n_samples)
                new_pop[:, root_var] = selected[donors, root_var]
                inject_novelty(root_var)
                continue

            # Non-root edge parent -> child.
            parent_var = int(cliques[c, 2])
            child_var = int(cliques[c, 3])

            # Value already assigned to the parent in each new individual.
            parent_vals = new_pop[:, parent_var]

            # Block of PopulValues[:, parent] holding donors with X_parent = v:
            #   rows [cum[v], cum[v+1]).
            cum = parent_indices[parent_var]
            starts = cum[parent_vals]
            ends = cum[parent_vals + 1]
            sizes = ends - starts

            # Each parent value came from a real donor, so blocks are non-empty.
            # Guard defensively anyway: any (impossible) empty block falls back
            # to a uniform donor over the whole selected set.
            empty = sizes <= 0
            if np.any(empty):
                sizes = np.where(empty, n_selected, sizes)
                starts = np.where(empty, 0, starts)

            # Uniform random row inside each block.
            offsets = (rng.random(n_samples) * sizes).astype(np.int64)
            offsets = np.minimum(offsets, sizes - 1)  # guard against rng == 1.0
            rows = starts + offsets

            donors = popul_values[rows, parent_var]
            new_pop[:, child_var] = selected[donors, child_var]
            inject_novelty(child_var)

        if np.any(new_pop < 0):
            missing = np.unique(np.where(new_pop < 0)[1])
            raise RuntimeError(
                f"Int_FDA sampling left variables unassigned: {missing.tolist()}. "
                "The model's tree does not cover every variable."
            )

        return new_pop
